const photos=[{src:'./assets/hardware.jpg',alt:'Zerobionic builder holding a robotic hand',caption:'Zerobionic / Meet the builders',position:'62% center'},{src:'./assets/nairobi.jpg',alt:'Nairobi skyline — editorial sample',caption:'Nairobi / Editorial sample',position:'center'},{src:'./assets/street.jpg',alt:'Nairobi street scene — editorial sample',caption:'Everyday stories / Editorial sample',position:'center'}];
const track=document.querySelector('#photo-track'),strip=document.querySelector('#photo-strip'),dialog=document.querySelector('#photo-dialog');let selected=0;
function viewPhoto(i){selected=(i+photos.length)%photos.length;const p=photos[selected];document.querySelector('#viewer-image').src=p.src;document.querySelector('#viewer-image').alt=p.alt;document.querySelector('#viewer-caption').textContent=`${String(selected+1).padStart(2,'0')} / ${String(photos.length).padStart(2,'0')} — ${p.caption}`;}
for(let group=0;group<3;group++){const row=document.createElement('div');row.className='photo-group';if(group>0)row.setAttribute('aria-hidden','true');photos.forEach((p,i)=>{const button=document.createElement('button');button.className='photo-card';button.style.setProperty('--tilt',`${[-3,2,-2][i]}deg`);button.setAttribute('aria-label',`View ${p.caption}`);if(group>0)button.tabIndex=-1;const img=document.createElement('img');img.src=p.src;img.alt=p.alt;img.style.objectPosition=p.position;img.draggable=false;const label=document.createElement('span');label.textContent=p.caption;button.append(img,label);button.addEventListener('click',()=>{viewPhoto(i);dialog.showModal();document.body.style.overflow='hidden'});row.append(button)});track.append(row)}
function closeViewer(){dialog.close()}dialog.addEventListener('close',()=>document.body.style.overflow='');document.querySelector('.viewer-close').addEventListener('click',closeViewer);dialog.addEventListener('click',e=>{if(e.target===dialog)closeViewer()});document.querySelector('#viewer-prev').addEventListener('click',()=>viewPhoto(selected-1));document.querySelector('#viewer-next').addEventListener('click',()=>viewPhoto(selected+1));dialog.addEventListener('keydown',e=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();viewPhoto(selected+(e.key==='ArrowRight'?1:-1))}});
const motion=matchMedia('(prefers-reduced-motion: reduce)'),toggle=document.querySelector('#motion-toggle');let paused=motion.matches,hovered=false,focused=false,touching=false,last=0,visible=true;
function label(){toggle.textContent=paused?'Resume motion ▶':'Pause motion Ⅱ';toggle.setAttribute('aria-pressed',String(paused))}label();toggle.addEventListener('click',()=>{paused=!paused;label()});motion.addEventListener('change',e=>{paused=e.matches;label()});strip.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse')hovered=true});strip.addEventListener('pointerleave',()=>hovered=false);strip.addEventListener('focusin',()=>focused=true);strip.addEventListener('focusout',e=>{focused=strip.contains(e.relatedTarget)});strip.addEventListener('touchstart',()=>touching=true,{passive:true});strip.addEventListener('touchend',()=>{setTimeout(()=>touching=false,2500)},{passive:true});strip.addEventListener('touchcancel',()=>touching=false,{passive:true});new IntersectionObserver(entries=>visible=entries[0].isIntersecting).observe(strip);
function animate(t){const delta=Math.min(t-last,40);last=t;if(!paused&&!hovered&&!focused&&!touching&&!dialog.open&&visible&&!document.hidden){strip.scrollLeft+=delta*.035;const width=track.firstElementChild.getBoundingClientRect().width;if(strip.scrollLeft>=width)strip.scrollLeft-=width}requestAnimationFrame(animate)}requestAnimationFrame(animate);
document.querySelectorAll('.video-cover').forEach(button=>button.addEventListener('click',()=>{const player=button.parentElement,frame=document.createElement('iframe');frame.src=`https://www.youtube-nocookie.com/embed/${player.dataset.video}?autoplay=1&rel=0`;frame.title=player.dataset.title;frame.allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share';frame.allowFullscreen=true;frame.referrerPolicy='strict-origin-when-cross-origin';player.replaceChildren(frame);frame.focus()}));
